name: Run tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

jobs:
  test-otio-0140:
    env:
      plugin_name: "otio_avb_plugin"

    name: "OpenTimelineIO 0.14.0"
    strategy:
      matrix:
        python-version: ["2.7", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov pyavb -V OpenTimelineIO==0.14.1

      - name: Install Plugin
        run: |
          pip install -e .

      - name: Lint with flake8
        run: |
          flake8 --show-source --statistics

      - name: Test with pytest
        run: |
          pytest -v

        shell: bash
